### ISSUE TITLE
Setup GitHub pages for hosting

### ISSUE THREAD

**Issue by Glavin001** [chadams77/RNCAL-NS#1]
See https://pages.github.com/

It would be great to view this project without needing to clone and run locally! It looks like everything is static frontend code?

**Comment by chadams77** [comment]
Yeah everything is static, the data files are about 27mb total though

**Comment by chadams77** [comment]
Looks like the data can be redistributed provided the sources and licenses are linked, so I added that to the README

**Comment by chadams77** [comment]
Ok it's live on github pages, see the README on the repo page
